[package]
name = "rocketsim_rs"
version = "0.37.0"
edition = "2024"
description = "Rust bindings for the RocketSim project"
repository = "https://github.com/VirxEC/rocketsim-rs"
license = "MIT"
exclude = [
  "*.py",
  ".git*",
  "CMake*",
  "MANIFEST.in",
  "collision_meshes",
  "python",
  "rustfmt.toml",
  "tests"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "rlviser_socket"
required-features = ["bin"]

[[example]]
name = "rlviser_stress"
required-features = ["bin"]

[dependencies]
cxx = { version = "1.0.130", features = ["c++20"] }
glam = { version = "0.33.0", optional = true }
planus = { git = "https://github.com/swz-git/planus", rev = "a0b1fbf", optional = true }
serde = { version = "1.0.195", features = ["derive"], optional = true }

[dev-dependencies]
byteorder = "1.4.3"
ctrlc = "3.3.1"
rand = "0.10.0"
serde_json = "1.0.111"

[build-dependencies]
cc = { version = "1.2.37", features = ["parallel"] }
cxx-build = "1.0.130"
glob = "0.3.0"
planus-codegen = { git = "https://github.com/swz-git/planus", rev = "a0b1fbf", optional = true }
planus-translation = { git = "https://github.com/swz-git/planus", rev = "a0b1fbf", optional = true }

[target.'cfg(not(any(target_arch = "x86", target_arch = "x86_64")))'.dependencies]
# use glam with experimental support for portable SIMD when not running on x86
# architectures
glam = { version = "0.33.0", features = ["core-simd"], optional = true }

[features]
default = ["bin", "debug_logging"]
bin = ["serde", "dep:planus", "dep:planus-codegen", "dep:planus-translation"]
debug_logging = []
glam = ["dep:glam"]
serde_utils = ["serde"]

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
